# mode: "agent"
# agent:
#   interval: 5 #5 segundos cada request
#   watchers:
#     teste:
#       addr: "http://dev.madeiramadeira.com.br:60013/supplier/alive"
#       method: "http"  

mode: "server"
server:
  addr: "127.0.0.1"
  port: "9777"